# Generated by Django 4.1.3 on 2023-01-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('ci', models.IntegerField()),
                ('grupo', models.IntegerField(max_length=4)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
    ]
