# Generated by Django 4.1.5 on 2023-01-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('ci', models.IntegerField(max_length=11, unique=True)),
                ('grupo', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=15)),
                ('duracion', models.DurationField()),
                ('modalidad', models.CharField(max_length=15)),
                ('resultado', models.CharField(max_length=10)),
                ('autor', models.ManyToManyField(blank=True, to='proyecto_final.artista')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
    ]
