# Generated by Django 4.1.3 on 2023-01-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='grupo',
            field=models.IntegerField(),
        ),
    ]
