# Generated by Django 4.1.3 on 2023-01-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_final', '0002_alter_artist_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.AlterField(
            model_name='artist',
            name='ci',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
