# Generated by Django 4.1.3 on 2023-01-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_final', '0003_remove_artist_id_alter_artist_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento_resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artista', models.CharField(max_length=50)),
                ('nombre_obra', models.CharField(max_length=50)),
                ('modalidad', models.CharField(max_length=15)),
                ('resultado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=15)),
                ('duracion', models.DurationField()),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
    ]
