# Generated by Django 4.1.3 on 2023-01-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_final', '0004_evento_resultado_modalidad_obra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Artista',
        ),
    ]
