# Generated by Django 4.1.3 on 2023-01-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_final', '0005_rename_artist_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artista',
            name='ci',
            field=models.IntegerField(verbose_name=123),
        ),
    ]
