# Generated by Django 4.1.3 on 2023-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_final', '0007_alter_artista_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
