# Generated by Django 4.1.3 on 2023-01-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_final', '0008_alter_artista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
